# ML Pipeline Preparation
Follow the instructions below to help you create your ML pipeline.
### 1. Import libraries and load data from database.
- Import Python libraries
- Load dataset from database with [`read_sql_table`](https://pandas.pydata.org/pandas-docs/stable/generated/pandas.read_sql_table.html)
- Define feature and target variables X and Y

In [229]:
# import libraries

import pandas as pd
import numpy as np
from sqlalchemy import create_engine

import re
import nltk
from nltk.tokenize import word_tokenize
from nltk.tokenize import sent_tokenize
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
from nltk.stem.wordnet import WordNetLemmatizer

nltk.download('punkt')
nltk.download('stopwords')
nltk.download('wordnet')

import sklearn
from sklearn.pipeline import Pipeline
from sklearn.metrics import confusion_matrix
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.feature_extraction.text import CountVectorizer, TfidfTransformer
from sklearn.model_selection import GridSearchCV
from sklearn.metrics.scorer import make_scorer

import pickle

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\livel\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\livel\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\livel\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!


In [2]:
# load data from database
engine = create_engine('sqlite:///database.db')
df = pd.read_sql_table('data',con=engine)

In [3]:
print(df.head())

                                             message  \
0  Weather update - a cold front from Cuba that c...   
1            Is the Hurricane over or is it not over   
2                    Looking for someone but no name   
3  UN reports Leogane 80-90 destroyed. Only Hospi...   
4  says: west side of Haiti, rest of the country ...   

                                            original   genre  related  \
0  Un front froid se retrouve sur Cuba ce matin. ...  direct        1   
1                 Cyclone nan fini osinon li pa fini  direct        1   
2  Patnm, di Maryani relem pou li banm nouvel li ...  direct        1   
3  UN reports Leogane 80-90 destroyed. Only Hospi...  direct        1   
4  facade ouest d Haiti et le reste du pays aujou...  direct        1   

   request  offer  aid_related  medical_help  medical_products  \
0        0      0            0             0                 0   
1        0      0            1             0                 0   
2        0      0         

In [4]:
X = df.iloc[:,0]
Y = df.iloc[:,3:]

In [31]:
print(Y)

       related  request  offer  aid_related  medical_help  medical_products  \
0            1        0      0            0             0                 0   
1            1        0      0            1             0                 0   
2            1        0      0            0             0                 0   
3            1        1      0            1             0                 1   
4            1        0      0            0             0                 0   
...        ...      ...    ...          ...           ...               ...   
26210        0        0      0            0             0                 0   
26211        0        0      0            0             0                 0   
26212        1        0      0            0             0                 0   
26213        1        0      0            1             0                 0   
26214        1        0      0            0             0                 0   

       search_and_rescue  security  military  child

### 2. Write a tokenization function to process your text data

In [9]:
def tokenize(text):
    
    text = re.sub(r"[^a-zA-Z0-9]", " ",text).lower()
    text = word_tokenize(text)
    text =  [w for w in text if w not in stopwords.words("english")]
    text = [PorterStemmer().stem(w) for w in text]
    text = [WordNetLemmatizer().lemmatize(w) for w in text]
    
    return text

### 3. Build a machine learning pipeline
This machine pipeline should take in the `message` column as input and output classification results on the other 36 categories in the dataset. You may find the [MultiOutputClassifier](http://scikit-learn.org/stable/modules/generated/sklearn.multioutput.MultiOutputClassifier.html) helpful for predicting multiple target variables.

In [240]:
'''
pipeline = Pipeline([
    ('vect', CountVectorizer(tokenizer=tokenize)),
    ('ifidf', TfidfTransformer()),
    ('clf', RandomForestClassifier())
])
'''

In [298]:
def preprocess(X):
    
    vectorizer = CountVectorizer(tokenizer=tokenize)
    X = vectorizer.fit_transform(X)
    tfidf = TfidfTransformer()
    X = tfidf.fit_transform(X)
    
    return X, vectorizer, tfidf

In [301]:
def preprocess_test(X, vectorizer,tfidf):
    
    X = vectorizer.transform(X)
    X = tfidf.transform(X)
    
    return X

In [379]:
def train(X, y):
    
    clfs = [] 
    error_cols = []
    
    num_col = y.shape[1]
    
    print('num_col:', num_col)
   
    for i in range(num_col):
 
        print('i:', i)
        clf = LogisticRegression(class_weight='balanced')
        #clf = RandomForestClassifier()
        
        try:
            clf.fit(X, y.iloc[:,i])
        except:
            print('col:', i, ' caused error')
            error_cols.append(i)
    
        clfs.append(clf)
    
    return clfs, num_col, error_cols


In [380]:

def pipeline_orig(X, y): 
    
    X, vectorizer, tfidf = preprocess(X)
    
    clfs, num_col, error_cols = train(X, y)
    
    return clfs, num_col, error_cols, vectorizer, tfidf


### 4. Train pipeline
- Split data into train and test sets
- Train pipeline

In [381]:
X_train, X_test, y_train, y_test = train_test_split(X, Y)

In [382]:
#pipeline.fit(X_train, y_train.iloc[:,0].values)

clfs, num_col, error_cols, vectorizer, tfidf = pipeline_orig(X_train, y_train)

num_col: 36
i: 0


C:\Users\livel\Miniconda3\lib\site-packages\sklearn\linear_model\_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


i: 1
i: 2
i: 3
i: 4
i: 5
i: 6
i: 7
i: 8
i: 9
col: 9  caused error
i: 10
i: 11
i: 12
i: 13
i: 14
i: 15
i: 16
i: 17
i: 18
i: 19
i: 20
i: 21
i: 22
i: 23
i: 24
i: 25
i: 26
i: 27
i: 28
i: 29
i: 30
i: 31
i: 32
i: 33
i: 34
i: 35


C:\Users\livel\Miniconda3\lib\site-packages\sklearn\linear_model\_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


### 5. Test your model
Report the f1 score, precision and recall for each output category of the dataset. You can do this by iterating through the columns and calling sklearn's `classification_report` on each.

In [383]:
def predict(clfs, X, num_col, error_cols, vectorizer, tfidf):
    
    print('num_col:', num_col)
    print('error_cols:', error_cols)
    
    result = []
    
    X_prep = preprocess_test(X, vectorizer, tfidf)
    
    for i in range(num_col):
        
        print('i:',i)
       
        if i in error_cols:        
            pred = np.zeros(len(X))
        
        else:
            clf = clfs[i]  
            pred = clf.predict(X_prep)
        
        result.append(pred)
     
    result = np.array(result)
    result = np.transpose(result)
    
    return result
    

In [384]:
y_pred = predict(clfs, X_test, num_col, error_cols, vectorizer, tfidf)
print(y_pred)

num_col: 36
error_cols: [9]
i: 0
i: 1
i: 2
i: 3
i: 4
i: 5
i: 6
i: 7
i: 8
i: 9
i: 10
i: 11
i: 12
i: 13
i: 14
i: 15
i: 16
i: 17
i: 18
i: 19
i: 20
i: 21
i: 22
i: 23
i: 24
i: 25
i: 26
i: 27
i: 28
i: 29
i: 30
i: 31
i: 32
i: 33
i: 34
i: 35
[[1. 0. 0. ... 0. 0. 1.]
 [1. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 1. 1.]
 [1. 0. 0. ... 0. 1. 0.]]


In [385]:
#y_pred = pipeline.predict(X_test)

In [386]:
label_pred = y_pred
print(label_pred)
print(label_pred.sum(), len(label_pred))

[[1. 0. 0. ... 0. 0. 1.]
 [1. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 1. 1.]
 [1. 0. 0. ... 0. 1. 0.]]
28320.0 6554


In [387]:
def display_results(y_test, y_pred):
    
    try: 
        num_col = num_col = y_pred.shape[1]
    except: 
        num_col = 1
        
    labels = Y.columns
    
    accuracies = [] 
    fvalues = []
    
    for i in range(num_col):
        
        
        pred = y_pred[:,i]
        test = y_test[:,i]
        
        '''
        except:
            pred = y_pred
            test = y_test
            print('except!')
        '''
        
        tp = np.logical_and(test, pred).sum()
        fp = np.logical_and(1-test, pred).sum()
        tn = np.logical_and(1-test, 1-pred).sum()
        fn = np.logical_and(test, 1-pred).sum()

        acc = (tp + tn) / (tp + fp + tn + fn)
    
        recall = tp / (tp + fn)
        prec = tp / (tp + fp)
        fval = 2 * recall * prec / (recall + prec)
                
        conf_matrix = [[tp, fp],[fn, tn]]
    
        print('label:', labels[i] ,'\naccuracy:', acc, '\nf-value:', fval)
        #print('confusion matrix:')
        #print(conf_matrix[0])
        #print(conf_matrix[1])
        
        #print('\n\n')
        
        accuracies.append(acc)
        fvalues.append(fval)
        
    
    print('average accuracy:', sum(accuracies) / len(accuracies))
    
    fvalues = [x for x in fvalues if x == x]
    
    ave_fvalues = sum(fvalues) / len(fvalues)
    
    print('average f score:', ave_fvalues)
    #print("Labels:", labels)
    #print("Accuracy:", accuracy)
    #print("Confusion Matrix:\n", confusion_mat)
    
    return ave_fvalues

In [388]:
print(y_test.shape, type(y_test))
print(y_pred.shape, type(y_pred))

(6554, 36) <class 'pandas.core.frame.DataFrame'>
(6554, 36) <class 'numpy.ndarray'>


In [389]:
print(y_pred)

[[1. 0. 0. ... 0. 0. 1.]
 [1. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 1. 1.]
 [1. 0. 0. ... 0. 1. 0.]]


In [390]:
print(display_results(y_test.values, y_pred))

label: related 
accuracy: 0.796982372273678 
f-value: 0.8567815365159659
label: request 
accuracy: 0.8613060726274031 
f-value: 0.6371257485029939
label: offer 
accuracy: 0.9795544705523345 
f-value: 0.05633802816901409
label: aid_related 
accuracy: 0.7790662191028379 
f-value: 0.7324464153732446
label: medical_help 
accuracy: 0.8864815379920659 
f-value: 0.48189415041782724
label: medical_products 
accuracy: 0.909368324687214 
f-value: 0.3987854251012146
label: search_and_rescue 
accuracy: 0.9267622825755264 
f-value: 0.2727272727272727
label: security 
accuracy: 0.9369850472993592 
f-value: 0.12684989429175475
label: military 
accuracy: 0.9540738480317363 
f-value: 0.5121555915721232
label: child_alone 
accuracy: 1.0 
f-value: nan
label: water 
accuracy: 0.9493439121147391 
f-value: 0.6757812500000001
label: food 
accuracy: 0.9418675617943241 
f-value: 0.761128526645768
label: shelter 
accuracy: 0.9227952395483674 
f-value: 0.6257396449704141
label: clothing 
accuracy: 0.983063777845

C:\Users\livel\Miniconda3\lib\site-packages\ipykernel_launcher.py:33: RuntimeWarning: invalid value encountered in long_scalars
C:\Users\livel\Miniconda3\lib\site-packages\ipykernel_launcher.py:34: RuntimeWarning: invalid value encountered in long_scalars


### 6. Improve your model
Use grid search to find better parameters. 

In [213]:
print(sorted(sklearn.metrics.SCORERS.keys()))

['accuracy', 'adjusted_mutual_info_score', 'adjusted_rand_score', 'average_precision', 'balanced_accuracy', 'completeness_score', 'explained_variance', 'f1', 'f1_macro', 'f1_micro', 'f1_samples', 'f1_weighted', 'fowlkes_mallows_score', 'homogeneity_score', 'jaccard', 'jaccard_macro', 'jaccard_micro', 'jaccard_samples', 'jaccard_weighted', 'max_error', 'mutual_info_score', 'neg_brier_score', 'neg_log_loss', 'neg_mean_absolute_error', 'neg_mean_gamma_deviance', 'neg_mean_poisson_deviance', 'neg_mean_squared_error', 'neg_mean_squared_log_error', 'neg_median_absolute_error', 'neg_root_mean_squared_error', 'normalized_mutual_info_score', 'precision', 'precision_macro', 'precision_micro', 'precision_samples', 'precision_weighted', 'r2', 'recall', 'recall_macro', 'recall_micro', 'recall_samples', 'recall_weighted', 'roc_auc', 'roc_auc_ovo', 'roc_auc_ovo_weighted', 'roc_auc_ovr', 'roc_auc_ovr_weighted', 'v_measure_score']


In [222]:
parameters = {
    'clf__max_depth': [10],
    'clf__n_estimators': [200],
    'clf__min_samples_leaf': [1, 2, 5, 10]
    }

my_scorer = make_scorer(display_results, greater_is_better=True)

CV = GridSearchCV(pipeline, parameters, scoring=my_scorer, n_jobs= 1)

In [223]:
print(X_train.head())

11046    I am not a professional but have experience wi...
12798    Hurricane Recovery. (@Pig 'n' Whistle w/ 9 oth...
8749     Patricia tresil from Mirebalais, Barcelona Fan...
15771    Over 230 specialist eye care nurses and occupa...
25107    Food riots erupted in Bhubaneswar, the state c...
Name: message, dtype: object


In [224]:
CV.fit(X_train, y_train.iloc[:,0].values)

label: related 
accuracy: 0.7616763443574854 
f-value: 0.8647176841501862
confusion matrix:
[3017, 944]
[0, 0]



average accuracy: 0.7616763443574854
average f score: 0.8647176841501862
label: related 
accuracy: 0.7618085375094721 
f-value: 0.8648028673835125
confusion matrix:
[3016, 943]
[0, 0]



average accuracy: 0.7618085375094721
average f score: 0.8648028673835125
label: related 
accuracy: 0.7618085375094721 
f-value: 0.8648028673835125
confusion matrix:
[3016, 943]
[0, 0]



average accuracy: 0.7618085375094721
average f score: 0.8648028673835125
label: related 
accuracy: 0.7616161616161616 
f-value: 0.8646788990825688
confusion matrix:
[3016, 944]
[0, 0]



average accuracy: 0.7616161616161616
average f score: 0.8646788990825688
label: related 
accuracy: 0.7616161616161616 
f-value: 0.8646788990825688
confusion matrix:
[3016, 944]
[0, 0]



average accuracy: 0.7616161616161616
average f score: 0.8646788990825688
label: related 
accuracy: 0.7616763443574854 
f-value: 0.86471768

KeyboardInterrupt: 

### 7. Test your model
Show the accuracy, precision, and recall of the tuned model.  

Since this project focuses on code quality, process, and  pipelines, there is no minimum performance metric needed to pass. However, make sure to fine tune your models for accuracy, precision and recall to make your project stand out - especially for your portfolio!

In [110]:
y_pred_improved = CV.predict(X_test.values)

AttributeError: 'GridSearchCV' object has no attribute 'best_estimator_'

In [ ]:
display_results(y_test[:,0], y_pred_improved)

### 8. Try improving your model further. Here are a few ideas:
* try other machine learning algorithms
* add other features besides the TF-IDF

In [225]:
pipelineLR = Pipeline([
    ('vect', CountVectorizer(tokenizer=tokenize)),
    ('ifidf', TfidfTransformer()),
    ('clf', LogisticRegression(class_weight='balanced'))
])

In [226]:
pipelineLR.fit(X_train.values, y_train.iloc[:,0].values)

C:\Users\livel\Miniconda3\lib\site-packages\sklearn\linear_model\_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


Pipeline(memory=None,
         steps=[('vect',
                 CountVectorizer(analyzer='word', binary=False,
                                 decode_error='strict',
                                 dtype=<class 'numpy.int64'>, encoding='utf-8',
                                 input='content', lowercase=True, max_df=1.0,
                                 max_features=None, min_df=1,
                                 ngram_range=(1, 1), preprocessor=None,
                                 stop_words=None, strip_accents=None,
                                 token_pattern='(?u)\\b\\w\\w+\\b',
                                 tokenizer=<function tokenize at...
                ('ifidf',
                 TfidfTransformer(norm='l2', smooth_idf=True,
                                  sublinear_tf=False, use_idf=True)),
                ('clf',
                 LogisticRegression(C=1.0, class_weight='balanced', dual=False,
                                    fit_intercept=True, intercept_scaling

In [118]:
y_pred_improved2 = pipelineLR.predict(X_test.values)

In [227]:
print(display_results(y_test[:,0], y_pred_improved2))

label: related 
accuracy: 0.5943183526228769 
f-value: 0.7201078502540703
confusion matrix:
[3472, 1122]
[1577, 482]



average accuracy: 0.5943183526228769
average f score: 0.7201078502540703
0.7201078502540703


### 9. Export your model as a pickle file

In [391]:
#save_model = pipeline
save_model = clfs
filename = 'finalized_model.pkl'
pickle.dump(save_model, open(filename, 'wb'))

In [233]:
model_path = '../deploy/models/finalized_model.pkl'
loaded = pickle.load(open(model_path, 'rb'))

In [239]:
text = ["test textd fdajiji longeter ga jijigotk aidhgdaai earth quake t textd fdajiji longeter ga jijigotk aidhgdaai earth quake"]

result = loaded.predict(text)

print(result)

[1]


### 10. Use this notebook to complete `train.py`
Use the template file attached in the Resources folder to write a script that runs the steps above to create a database and export a model based on a new dataset specified by the user.